/**
 * OCR Quality Analysis — Core Types
 *
 * Single source of truth for OCR Quality Report, Quality Warnings,
 * Quality Recommendations, Content Detection, Confidence Breakdown, and
 * Configurable Weights.
 *
 * Version: 2.1
 */

export const QUALITY_PIPELINE_VERSION = '2.1';

// ─────────────────────────────────────────────────────────────────────────────
// Content Type Classification & Detection
// ─────────────────────────────────────────────────────────────────────────────

export type ContentType =
  | 'code'
  | 'markdown'
  | 'json'
  | 'html'
  | 'yaml'
  | 'terminal'
  | 'prose'
  | 'mixed'
  | 'empty'
  | 'unknown';

export interface ContentDetection {
  /** Primary content classification */
  type:       ContentType;
  /** Classification confidence percentage (0–100) */
  confidence: number;
  /** Specific syntactic evidence tags found in the text */
  evidence:   string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Quality Warning
// ─────────────────────────────────────────────────────────────────────────────

export type QualityWarningSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface QualityWarning {
  /** Machine-readable warning type */
  type:     string;
  /** Severity level for downstream retry heuristics */
  severity: QualityWarningSeverity;
  /** Human-readable explanation */
  message:  string;
  /** Optional metadata details */
  details?: Record<string, unknown>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Quality Recommendation
// ─────────────────────────────────────────────────────────────────────────────

export type QualityRecommendationAction =
  | 'AcceptResult'
  | 'RetryRecommended'
  | 'UseCodeProfile'
  | 'UseDocumentProfile'
  | 'IncreaseContrast'
  | 'UpscaleImage'
  | 'LowConfidence';

export const RECOMMENDATION_PRIORITY: Record<QualityRecommendationAction, number> = {
  RetryRecommended:   100,
  UseCodeProfile:     80,
  UseDocumentProfile: 80,
  IncreaseContrast:   60,
  UpscaleImage:       60,
  LowConfidence:      50,
  AcceptResult:       10,
};

export interface QualityRecommendation {
  /** Recommended action tag */
  type:              QualityRecommendationAction;
  /** Priority numeric rank (higher value = higher execution priority) */
  priority:          number;
  /** Human-readable explanation of why this action is recommended */
  reason:            string;
  /** Optional suggested profile name */
  suggestedProfile?: string;
  /** Metadata parameters for the retry engine */
  metadata?:         Record<string, unknown>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Configurable Analyzer Weights
// ─────────────────────────────────────────────────────────────────────────────

export interface QualityAnalyzerWeights {
  engineConfidence: number; // default 0.35
  imageQuality:     number; // default 0.15
  characterQuality: number; // default 0.25
  structureQuality: number; // default 0.15
  contentQuality:   number; // default 0.10
}

export const DEFAULT_QUALITY_WEIGHTS: QualityAnalyzerWeights = {
  engineConfidence: 0.35,
  imageQuality:     0.15,
  characterQuality: 0.25,
  structureQuality: 0.15,
  contentQuality:   0.10,
};

// ─────────────────────────────────────────────────────────────────────────────
// Confidence Breakdown
// ─────────────────────────────────────────────────────────────────────────────

export interface ConfidenceBreakdown {
  engineContribution:    number; // e.g. +30
  imageContribution:     number; // e.g. +14
  characterContribution: number; // e.g. +24
  structureContribution: number; // e.g. +14
  contentContribution:   number; // e.g. +9
  penalties:             number; // e.g. -10
  finalScore:            number; // e.g. 81
}

// ─────────────────────────────────────────────────────────────────────────────
// Individual Analyzer Output
// ─────────────────────────────────────────────────────────────────────────────

export interface AnalyzerResult {
  /** Name of the analyzer module */
  name:     string;
  /** Score from 0 (terrible) to 100 (perfect) */
  score:    number;
  /** Weight factor for overall quality aggregation (0.0 – 1.0) */
  weight:   number;
  /** Warnings generated by this analyzer */
  warnings: QualityWarning[];
  /** Detailed metrics collected during analysis */
  details:  Record<string, unknown>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Full OCR Quality Report
// ─────────────────────────────────────────────────────────────────────────────

export interface OCRQualityReport {
  /** Quality heuristic version */
  qualityPipelineVersion: string;

  /** Composite overall quality score (0–100) */
  overallScore: number;

  /** Raw engine recognition confidence (0–100) */
  recognitionConfidence: number;

  /** Preprocessing image quality score (0–100) */
  imageQualityScore: number;

  /** Character-level quality score (0–100) */
  characterScore: number;

  /** Layout & structure quality score (0–100) */
  structureScore: number;

  /** Content consistency score (0–100) */
  contentScore: number;

  /** Enriched Content Detection model */
  contentDetection: ContentDetection;

  /** Structured contribution & penalty breakdown */
  confidenceBreakdown: ConfidenceBreakdown;

  /** All structured warnings collected across analyzers */
  warnings: QualityWarning[];

  /** Priority-sorted recommendations */
  recommendations: QualityRecommendation[];

  /** Granular diagnostic metrics */
  metrics: Record<string, unknown>;

  /** Execution time of quality analysis in milliseconds */
  analysisTimeMs: number;
}
